-- AlterTable
ALTER TABLE "SubscriptionPlan" ADD COLUMN "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 21;

-- AlterTable
ALTER TABLE "PaymentRecord" ADD COLUMN "vatRate" DOUBLE PRECISION NOT NULL DEFAULT 21;
